project:
  type: website
  output-dir: docs  # This is the new line to specify the output directory

website:
  title: "AlexPaulKelly"

navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/resolver101757
      - icon: twitter
        href: https://twitter.com/alex_paul_kelly
format:
  html:
    theme: cosmo
    css: styles.css