# title : Who is hugging face and why use their learn the the dataset loader

# What is hugging face 

It's hard to pin down what hugging face is but if i had to say in a single line it would be a open source AI hub, however its much more than that. It is a digital space to share models, datasets and training scripts all of which is free to download and upload. It also has space for people to post projects where they host models in a gradio user interface whcih is a software library they have created.  

They're aim is to make it easy for people to do anything machine learning. To acheive these goals they provide a various software libraries, heres a few picks : 

- Transformer API is a python library that allows you to download and use pretrained models from the hugging face hub, customize them.  It also allows you to train your own models and upload them to the hub.

Blogs and tutorials are also hosted on the site that talk about all their offering services and how to use them but also whats new in the world of machine learning.  

# Dataset loader 

